# NUMPY FOR DATA SCIENCE

In [2]:
import numpy as np
from time import process_time


In [14]:
# Creating a simple dimension array
ages = np.array([12,13,34,15,16,17,18,24])


In [15]:
print(ages)
# checking the datatype
type(ages)
# Checking the number of dimensions
ages.shape
# Getting the number of elements
ages.size

[12 13 34 15 16 17 18 24]


8

In [20]:
# Changing from one dim to two dim figure
c=ages.reshape(2,4)

In [30]:
# creatind an array with initial values
arr2 =  np.zeros((2,3),dtype=int)
print(arr2)
arr2.dtype
type(arr2)
arr2.size

[[0 0 0]
 [0 0 0]]


6

In [40]:
# creating an array containing random numbers
rand = np.random.randint(10,20,(3,2))

In [43]:
rand.reshape((1,6))

array([[10, 13, 13, 19, 16, 18]])

In [44]:
# Creating an array having the same number of rows and columns
arr3=np.eye(4)

In [45]:
arr3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Creating an evenly spaced array
arr4=np.linspace(12,25,5,dtype=int)

In [49]:
arr4

array([12, 15, 18, 21, 25])

In [50]:
# Mathematical Operations(Arithmetic Operations)
# creating an array with random numbers in the range of 10-20,20-30
a = np.random.randint(10,20,(3,3))
b = np.random.randint(20,30,(3,3))

In [54]:
print(a)
print('-'*20)
print(b)

[[13 19 15]
 [17 13 17]
 [13 19 13]]
--------------------
[[29 25 26]
 [20 24 22]
 [21 27 28]]


In [69]:
trans=np.transpose(a)
print(trans)
# or
tra = b.T
print(tra)

[[13 17 13]
 [19 13 19]
 [15 17 13]]
[[29 20 21]
 [25 24 27]
 [26 22 28]]


In [68]:
# converting the list into an array
list = []
for i in range(1,12,2):
    list.append(i)

In [65]:
list
# Converting the list into an array
conv_list = np.asarray(list)

In [65]:
list
# Converting the list into an array
conv_list = np.asarray(list)

In [67]:
print(conv_list)

[ 1  3  5  7  9 11]
